name: cs236781-hw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # common
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - nodejs>=12.0
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-xdist
  - python=3.8.12
  - scikit-learn
  - scipy
  - tqdm
  - pip:
    - nbmerge
    - transformers
    - datasets
  # pytorch
  # Note for M1 macs: install this env with CONDA_SUBDIR=osx-64 (env var), as it
  # can't be installed for the native (osx-arm64) architecture.
  - pytorch=1.10.1
  - mkl<2022 # prevents crash when importing torch on M1 mac via rosetta2
  - torchvision=0.11.2
  - cudatoolkit=11.3
  - torchtext

platforms:
  - linux-64
